#ifndef MYLIMITS_H
#define MYLIMITS_H

#define MAX_NUMBER_STR_SIZE 20
#define MAX_WORD_SIZE 1001
#define MAX_MSG_SIZE (MAX_WORD_SIZE + 200)

#define MAX_QUEUE_NAME_SIZE 100

#define MAX_STATE 101
#define MAX_LETTER 27

#endif //MYLIMITS_H
